services:
  - type: web
    name: nepali-data-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    healthCheckPath: /
    plan: free
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
