services:
  - type: web
    name: nepali-data-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: free
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
