services:
  - type: web
    name: nepali-data-api
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: free
    autoDeploy: false
    # Explicitly handle port binding in simple_server.py
    # The simple_server.py handles binding to a port with fallback options
