services:
  - type: web
    name: nepali-data-api
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: free
    autoDeploy: true
